# Configuration for Label Actions - https://github.com/dessant/label-actions

apis:
  issues:
    comment: >
      Tagging the developer-platform team
#      @aptos-labs/developer-platform

blockchain:
  issues:
    comment: >
      Tagging the blockchain-eng team
#      @aptos-labs/blockchain-eng

cli:
  issues:
    comment: >
      Tagging cli code owner
#      @gregnazario

create-aptos-dapp:
  issues:
    comment: >
      Tagging CAD code owner
#      @0xmaayan

indexer:
  issues:
    comment: >
      Tagging the ecosystem-infra team
#      @aptos-labs/ecosystem-infra

move-and-smart-contracts:
  issues:
    comment: >
      Tagging the move-eng team
#      @aptos-labs/move-eng

nodes:
  issues:
    comment: >
      Tagging the prod-eng team
#      @aptos-labs/prod-eng

sdks:
  issues:
    comment: >
      Tagging the developer-platform team
#      @aptos-labs/developer-platform
